apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vpn-service
  template:
    metadata:
      labels:
        app: vpn-service
    spec:
      containers:
      - name: vpn-service
        image: jaysardar/vpn-service:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: vpn-service
spec:
  selector:
    app: vpn-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
